// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 187132f48ddf0f604882ba8213fe386f)
declare namespace Cloudflare {
	interface Env {
		ASSETS: Fetcher;
		FILES_BUCKET: R2Bucket;
	}
}
interface Env extends Cloudflare.Env {}
